name: Build, Test, Lint

on:
  [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle

      - name: Run tests
        run: ./gradlew test

      - name: Run ktlint
        run: ./gradlew ktlint